# Codecov Configuration

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%
  
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "alembic/**/*"
  - "app/__init__.py"
  - "app/main.py"
  - "**/__pycache__/**/*"

flags:
  unittests:
    paths:
      - app/
    carryforward: true
